### ISSUE TITLE
Cache keys

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/tc-lambda-auth0-proxy-server#7]
Right now it seems that the cache is keyed solely off of the clientId. This is fine when only using one audience. When switching between audiences, however, it fails to take the new audience into account and thus returns the wrong token for the original audience instead of the new audience. 
Proposed solution would be to combine the clientId w/ the audience as the cache key

**Comment by sachin-maheshwari** [comment]
Fixing in - https://github.com/topcoder-platform/tc-lambda-auth0-proxy-server/commit/b42430d5b40a65cf02fc52d64b009e6536ec5f5e

**Comment by sachin-maheshwari** [comment]
@cwdcwd good catch. Thanks!. 👍
